import sys
import json
import joblib
import warnings
import pandas as pd
import numpy as np
from pathlib import Path

# Silence scikit-learn warnings about lacking feature names in input arrays
warnings.filterwarnings("ignore", category=UserWarning)

# Define paths to artifacts generated by Step 11
PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = PROJECT_ROOT / "models"
MODEL_PATH = MODELS_DIR / "best_model.joblib"
SCALER_PATH = MODELS_DIR / "scaler.joblib"
MAPPING_PATH = MODELS_DIR / "label_mapping.json"

FEATURE_COLUMNS = [
    "num_processes",
    "average_burst",
    "burst_std",
    "min_burst",
    "max_burst",
    "arrival_rate",
    "average_priority",
    "priority_std",
    "short_job_ratio",
    "long_job_ratio",
]

def load_artifacts():
    import os
    override_model = os.environ.get("ML_MODEL_OVERRIDE")
    override_scaler = os.environ.get("ML_SCALER_OVERRIDE")
    
    target_model_path = Path(override_model) if override_model else MODEL_PATH
    target_scaler_path = Path(override_scaler) if override_scaler else SCALER_PATH
    
    if not target_model_path.exists() or not target_scaler_path.exists() or not MAPPING_PATH.exists():
        return None, None, None
    model = joblib.load(target_model_path)
    scaler = joblib.load(target_scaler_path)
    with open(MAPPING_PATH, 'r') as f:
        mapping = json.load(f)
    return model, scaler, mapping

def predict(features: list):
    try:
        model, scaler, mapping = load_artifacts()
        if model is None:
            return {"error": "Missing one or more required ML artifacts (model, scaler, mapping)."}
            
        if len(features) != 10:
            return {"error": f"Expected exactly 10 features, got {len(features)}"}
            
        # Convert to float and check for NaNs/Infs
        feat_array = np.array(features, dtype=float)
        if not np.all(np.isfinite(feat_array)):
            return {"error": "Features contain NaN or Inf values."}
            
        df = pd.DataFrame([feat_array], columns=FEATURE_COLUMNS)
        
        # Handle Feature Ablation
        import os
        ablated_feature = os.environ.get("ML_ABLATED_FEATURE")
        if ablated_feature and ablated_feature in df.columns:
            df = df.drop(columns=[ablated_feature])
        
        # Scale features
        scaled_features = scaler.transform(df)
        
        # Predict
        predicted_label = int(model.predict(scaled_features)[0])
        
        # Extract Confidence
        confidence = -1.0
        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(scaled_features)[0]
            confidence = float(np.max(probs))
            
        # Map label back to name
        reverse_mapping = {int(v): k for k, v in mapping.items()}
        scheduler_name = reverse_mapping.get(predicted_label, "Unknown")
        
        if scheduler_name == "Unknown":
            return {"error": f"Predicted label {predicted_label} not found in label_mapping."}
            
        return {
            "predicted_label": predicted_label,
            "scheduler": scheduler_name,
            "confidence": confidence
        }
        
    except Exception as e:
        return {"error": f"Prediction exception: {str(e)}"}

def main():
    if len(sys.argv) != 11:
        print(json.dumps({"error": f"Expected 10 arguments, got {len(sys.argv) - 1}"}))
        sys.exit(1)
        
    try:
        features = [float(arg) for arg in sys.argv[1:]]
    except ValueError:
        print(json.dumps({"error": "Failed to parse features as floats."}))
        sys.exit(1)
        
    result = predict(features)
    print(json.dumps(result))

if __name__ == "__main__":
    main()
